In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
casual_df=pd.read_csv('Casualties0514.csv')
accident_df=pd.read_csv('Accidents0514.csv')
vehicle_df=pd.read_csv('Vehicles0514.csv')

C:\Users\vignesh kumar\AppData\Local\Temp\ipykernel_10804\3558190798.py:2: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  accident_df=pd.read_csv('Accidents0514.csv')


In [4]:
first_df=pd.merge(casual_df,accident_df,on='Accident_Index')

In [5]:
df=pd.merge(first_df,vehicle_df,on='Accident_Index')

In [6]:
df.drop('LSOA_of_Accident_Location',axis=1,inplace=True)


In [7]:
df.dropna(subset=['Time'],axis=0,inplace=True)
df

Accident_Index  Vehicle_Reference_x  Casualty_Reference  \
0        200501BS00001                    1                   1   
1        200501BS00002                    1                   1   
2        200501BS00003                    2                   1   
3        200501BS00003                    2                   1   
4        200501BS00004                    1                   1   
...                ...                  ...                 ...   
4287588  2014984138414                    2                   2   
4287589  2014984139614                    1                   2   
4287590  2014984139614                    1                   2   
4287591  2014984139614                    2                   1   
4287592  2014984139614                    2                   1   

         Casualty_Class  Sex_of_Casualty  Age_of_Casualty  \
0                     3                1               37   
1                     2                1               37   
2                     1                1               62   
3                     1                1               62   
4                     3                1               30   
...                 ...              ...              ...   
4287588               1                1               44   
4287589               2                1               61   
4287590               2                1               61   
4287591               1                1               79   
4287592               1                1               79   

         Age_Band_of_Casualty  Casualty_Severity  Pedestrian_Location  \
0                           7                  2                    1   
1                           7                  3                    0   
2                           9                  3                    0   
3                           9                  3                    0   
4                           6                  3                    5   
...                       ...                ...                  ...   
4287588                     7                  2                    0   
4287589                     9                  3                    0   
4287590                     9                  3                    0   
4287591                    11                  3                    0   
4287592                    11                  3                    0   

         Pedestrian_Movement  ...  Was_Vehicle_Left_Hand_Drive?  \
0                          1  ...                             1   
1                          0  ...                             1   
2                          0  ...                             1   
3                          0  ...                             1   
4                          2  ...                             1   
...                      ...  ...                           ...   
4287588                    0  ...                             1   
4287589                    0  ...                             1   
4287590                    0  ...                             1   
4287591                    0  ...                             1   
4287592                    0  ...                             1   

         Journey_Purpose_of_Driver  Sex_of_Driver  Age_of_Driver  \
0                               15              2             74   
1                                1              1             42   
2                                1              1             35   
3                               15              1             62   
4                               15              2             49   
...                            ...            ...            ...   
4287588                          6              1             73   
4287589                          1              1             40   
4287590                          6              1             79   
4287591                          1              1             40   
4287592                          6      

In [8]:
df.isnull().values.any()

True

In [9]:
df.dropna(inplace=True)


In [10]:
df.isnull().values.any()
df.columns

Index(['Accident_Index', 'Vehicle_Reference_x', 'Casualty_Reference',
       'Casualty_Class', 'Sex_of_Casualty', 'Age_of_Casualty',
       'Age_Band_of_Casualty', 'Casualty_Severity', 'Pedestrian_Location',
       'Pedestrian_Movement', 'Car_Passenger', 'Bus_or_Coach_Passenger',
       'Pedestrian_Road_Maintenance_Worker', 'Casualty_Type',
       'Casualty_Home_Area_Type', 'Location_Easting_OSGR',
       'Location_Northing_OSGR', 'Longitude', 'Latitude', 'Police_Force',
       'Accident_Severity', 'Number_of_Vehicles', 'Number_of_Casualties',
       'Date', 'Day_of_Week', 'Time', 'Local_Authority_(District)',
       'Local_Authority_(Highway)', '1st_Road_Class', '1st_Road_Number',
       'Road_Type', 'Speed_limit', 'Junction_Detail', 'Junction_Control',
       '2nd_Road_Class', '2nd_Road_Number',
       'Pedestrian_Crossing-Human_Control',
       'Pedestrian_Crossing-Physical_Facilities', 'Light_Conditions',
       'Weather_Conditions', 'Road_Surface_Conditions',
       'Special_Condi

In [11]:
q3_df=pd.DataFrame(data=df,columns=['Longitude','Latitude','1st_Road_Class','2nd_Road_Class','Weather_Conditions'])

In [12]:
q3_df

Longitude   Latitude  1st_Road_Class  2nd_Road_Class  \
0        -0.191170  51.489096               3              -1   
1        -0.211708  51.520075               4               5   
2        -0.206458  51.525301               5              -1   
3        -0.206458  51.525301               5              -1   
4        -0.173862  51.482442               3              -1   
...            ...        ...             ...             ...   
4287588  -3.191397  54.990446               3               5   
4287589  -3.348426  55.106700               4               4   
4287590  -3.348426  55.106700               4               4   
4287591  -3.348426  55.106700               4               4   
4287592  -3.348426  55.106700               4               4   

         Weather_Conditions  
0                         2  
1                         1  
2                         1  
3                         1  
4                         1  
...                     ...  
4287588                   2  
4287589                   1  
4287590                   1  
4287591                   1  
4287592                   1  

[4287073 rows x 5 columns]

In [13]:
X=q3_df.drop('Weather_Conditions',axis=1)
y=q3_df['Weather_Conditions']

q3_df['Weather_Conditions'].unique()

array([ 2,  1,  9,  3,  8,  4,  5,  7,  6, -1], dtype=int64)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test= train_test_split(X,y)
X_train.head(20)


Longitude   Latitude  1st_Road_Class  2nd_Road_Class
4202750   0.612264  51.179303               3              -1
3888695  -4.918972  51.861547               4               6
4055612  -1.225727  54.653321               3               6
2424882  -0.046358  51.611322               3               6
1324434  -0.224292  51.696609               2               2
349516   -0.639296  51.537145               6               6
3102887  -4.210080  51.029379               3              -1
1186705  -1.490554  53.488416               3              -1
2167513  -1.017670  53.152144               5              -1
447464   -2.507186  51.457979               6               4
1600541  -2.301347  53.588176               3               5
3183432  -0.242875  51.515511               5               6
1631551  -1.555635  54.678660               3              -1
906979    0.907947  51.298065               1              -1
1786074  -0.420302  51.839504               1              -1
788866   -1.116571  52.667021               3              -1
2493142  -1.744459  54.641281               3               6
3735003  -0.617388  53.208528               3               4
3132370  -1.820998  50.771481               4               6
4042042  -1.529812  53.499652               6               6

In [16]:
from sklearn.tree import DecisionTreeClassifier

In [17]:
dtree= DecisionTreeClassifier()

In [18]:
dtree.fit(X_train.values,y_train.values)

DecisionTreeClassifier()

In [19]:
predictions= dtree.predict(X_test.values)

In [20]:
from sklearn.metrics import classification_report, confusion_matrix

In [21]:
print(classification_report(y_test.values,predictions))

              precision    recall  f1-score   support

          -1       0.81      0.79      0.80       111
           1       0.93      0.95      0.94    852579
           2       0.77      0.72      0.74    131756
           3       0.74      0.68      0.71      7508
           4       0.75      0.68      0.71     13746
           5       0.75      0.68      0.71     15336
           6       0.77      0.73      0.75      1415
           7       0.82      0.76      0.79      7799
           8       0.73      0.67      0.70     23174
           9       0.73      0.65      0.69     18345

    accuracy                           0.90   1071769
   macro avg       0.78      0.73      0.75   1071769
weighted avg       0.90      0.90      0.90   1071769



In [22]:
print(confusion_matrix(y_test.values,predictions))
q3_df

[[    88     15      2      0      2      2      1      0      1      0]
 [    19 812014  24781   1375   2477   2669    221    997   4468   3558]
 [     1  34457  94671    227    384    531     39    169    721    556]
 [     0   1884    307   5133     31     44     14      9     53     33]
 [     0   3691    513     33   9291     58      8     12     76     64]
 [     1   3883    643     41     69  10485      8     21    100     85]
 [     0    291     51      6     10      4   1037      2      8      6]
 [     0   1483    215     17     30     40      1   5952     31     30]
 [     0   6419    858     54     90     94     15     44  15492    108]
 [     0   5453    674     38     55     79      6     23    147  11870]]


Longitude   Latitude  1st_Road_Class  2nd_Road_Class  \
0        -0.191170  51.489096               3              -1   
1        -0.211708  51.520075               4               5   
2        -0.206458  51.525301               5              -1   
3        -0.206458  51.525301               5              -1   
4        -0.173862  51.482442               3              -1   
...            ...        ...             ...             ...   
4287588  -3.191397  54.990446               3               5   
4287589  -3.348426  55.106700               4               4   
4287590  -3.348426  55.106700               4               4   
4287591  -3.348426  55.106700               4               4   
4287592  -3.348426  55.106700               4               4   

         Weather_Conditions  
0                         2  
1                         1  
2                         1  
3                         1  
4                         1  
...                     ...  
4287588                   2  
4287589                   1  
4287590                   1  
4287591                   1  
4287592                   1  

[4287073 rows x 5 columns]

In [23]:
import pickle
pickle.dump(dtree, open("weather.pkl", "wb"))